export const themeColors = {
  background: "var(--color-background)",
  surface: "var(--color-surface)",
  sidebar: "var(--color-sidebar)",
  sidebarForeground: "var(--color-sidebar-foreground)",
  sidebarBorder: "var(--color-sidebar-border)",
  sidebarAccent: "var(--color-sidebar-accent)",
  sidebarAccentForeground: "var(--color-sidebar-accent-foreground)",
  sidebarMuted: "var(--color-sidebar-muted)",
  sidebarMutedForeground: "var(--color-sidebar-muted-foreground)",
  rail: "var(--color-rail)",
  bgAccent: "var(--color-bg-accent)",
  ink: "var(--color-ink)",
  inkSoft: "var(--color-ink-soft)",
  presenceOnline: "var(--color-presence-online)",
  presenceAway: "var(--color-presence-away)",
  presenceOffline: "var(--color-presence-offline)",
  border: "var(--color-border)",
  foreground: "var(--color-foreground)",
  mutedForeground: "var(--color-muted-foreground)",
  primary: "var(--color-primary)",
} as const;
